services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGUSER=${DB_USER}
    volumes:
      - data:/var/lib/postgres/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  backend:
    build: ./backend
    container_name: web_backend
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: web_frontend
    restart: always
    ports:
      - '5173:5173'
    volumes:
      - type: bind
        source: ./.env-react 
        target: /home/app/frontend/.env
    depends_on:
      - backend
  
  reverse_proxy:
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - backend
      - frontend

volumes:
  data: